#include "/Projekty/AVR projects/SmartRoom/SmartRoom/inc/gpio.h"

void GPIO_Init(void)
{
	SET_PIN_AS_OUTPUT(PORTB, PUMP_PIN);
	SET_PIN_AS_OUTPUT(PORTB, RELAY4_PIN);
	
	SET_PIN_AS_OUTPUT(PORTD, RELAY1_PIN);
	SET_PIN_AS_OUTPUT(PORTD, RELAY2_PIN);
	SET_PIN_AS_OUTPUT(PORTD, RELAY3_PIN);
	
	RESET_BIT(PORTB, PUMP_PIN);
	RESET_BIT(PORTD, RELAY1_PIN);
	RESET_BIT(PORTD, RELAY2_PIN);
	RESET_BIT(PORTD, RELAY3_PIN);
	RESET_BIT(PORTB, RELAY4_PIN);
}